package interfaz;

import clases.Jugador;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Juego extends javax.swing.JFrame {

    private Jugador jugad1;
    private Jugador jugad2;
    private int deuce;
    private int deuce2;

    public Juego() {

        setUndecorated(true); //Código para ocultar la bara de título
        initComponents();

        //Código para centrar la ventana en la pantalla
        setLocationRelativeTo(null);

        //Código para fijar el tamaño de la ventana
        setResizable(false);

        //Código para cambiar el titulo de la ventana
        setTitle("Code Kata - Tennis");

        //Código para modificar el icono de la ventana
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/IconoMarco.png")).getImage());

        //Codigo para colocar fondo a la ventana
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Imagenes/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, 470, 811);

        //Código para colocar la imagen del icono de la barra de titulo
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagenes/Bordado1.png"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(jLblIcono.getWidth(), jLblIcono.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLblIcono.setIcon(fondo3);
        this.repaint();

        //Código para colocar la imagen del boton minimizar
        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/imagenes/Minimizar1.png"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(jbtnMinimizar.getWidth(), jbtnMinimizar.getHeight(), Image.SCALE_AREA_AVERAGING));
        jbtnMinimizar.setIcon(fondo4);
        this.repaint();

        //Código para colocar la imagen del boton cerrar
        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/imagenes/Cerrar1.png"));
        Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(jbtnCerrar.getWidth(), jbtnCerrar.getHeight(), Image.SCALE_AREA_AVERAGING));
        jbtnCerrar.setIcon(fondo5);
        this.repaint();

        //Código para colocar la imagen del jugador 1
        ImageIcon fotoJugador1 = new ImageIcon(getClass().getResource("/imagenes/jugador1.png"));
        Icon juga1 = new ImageIcon(fotoJugador1.getImage().getScaledInstance(jlblFoto1.getWidth(), jlblFoto1.getHeight(), Image.SCALE_AREA_AVERAGING));
        jlblFoto1.setIcon(juga1);
        this.repaint();

        //Código para colocar la imagen del jugador 2
        ImageIcon fotoJugador2 = new ImageIcon(getClass().getResource("/imagenes/Jugador2.png"));
        Icon juga2 = new ImageIcon(fotoJugador2.getImage().getScaledInstance(jlblFoto2.getWidth(), jlblFoto2.getHeight(), Image.SCALE_AREA_AVERAGING));
        jlblFoto2.setIcon(juga2);
        this.repaint();

        //Código para colocar la imagen de la barra de titulo
        ImageIcon imagen6 = new ImageIcon(getClass().getResource("/imagenes/barra.jpg"));
        Icon fondo6 = new ImageIcon(imagen6.getImage().getScaledInstance(jLblBarra.getWidth(), jLblBarra.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLblBarra.setIcon(fondo6);
        this.repaint();

        String jugador1 = JOptionPane.showInputDialog(null, "Escriba el nombre del jugador 1", "Jugadores", JOptionPane.INFORMATION_MESSAGE);
        jlbljugador1.setText(jugador1);

        String jugador2 = JOptionPane.showInputDialog(null, "Escriba el nombre del jugador 2", "Jugadores", JOptionPane.INFORMATION_MESSAGE);
        jlbljugador2.setText(jugador2);

        jugad1 = new Jugador(jugador1);
        jugad2 = new Jugador(jugador2);

        jLabel5.setVisible(false);
        jLabel1.setVisible(true);
        jLabel7.setVisible(true);
        jLabel2.setVisible(false);
        jButton2.setEnabled(false);
        jButton1.setEnabled(false);

        deuce = 0;
        deuce2 = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        jbtnMinimizar = new javax.swing.JButton();
        jbtnCerrar = new javax.swing.JButton();
        jLblIcono = new javax.swing.JLabel();
        jLblBarra = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblFoto1 = new javax.swing.JLabel();
        jlblFoto2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jlbljugador1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlbljugador2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tennis");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 30));

        jbtnMinimizar.setBorder(null);
        jbtnMinimizar.setBorderPainted(false);
        jbtnMinimizar.setContentAreaFilled(false);
        jbtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnMinimizarMouseExited(evt);
            }
        });
        jbtnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 30));

        jbtnCerrar.setBorder(null);
        jbtnCerrar.setBorderPainted(false);
        jbtnCerrar.setContentAreaFilled(false);
        jbtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCerrarMouseExited(evt);
            }
        });
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 30, 30));
        getContentPane().add(jLblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 35, 29));

        jLblBarra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblBarra.setForeground(new java.awt.Color(255, 255, 255));
        jLblBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblBarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 29));

        jPanel1.setBackground(new java.awt.Color(204, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Juego", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jlblFoto1.setBackground(new java.awt.Color(255, 255, 255));
        jlblFoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblFoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("VS");

        jPanel2.setBackground(new java.awt.Color(102, 0, 255));
        jPanel2.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 51));
        jLabel6.setText("Marcador");

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel4.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DEUCE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(412, 56));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Ganador del SET:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Punto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Punto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setOpaque(false);

        jlbljugador1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbljugador1.setForeground(new java.awt.Color(255, 153, 51));
        jlbljugador1.setText("Jugador 1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbljugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbljugador1)
                .addContainerGap())
        );

        jPanel7.setOpaque(false);

        jlbljugador2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbljugador2.setForeground(new java.awt.Color(255, 153, 51));
        jlbljugador2.setText("Jugador 2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbljugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbljugador2)
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Comenzar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 255));
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblFoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblFoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jlblFoto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(65, 65, 65)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 460, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMinimizarMouseEntered
        //Código para colocar la imagen del boton minimizar
        ImageIcon imagen7 = new ImageIcon(getClass().getResource("/imagenes/Minimizar2.png"));
        Icon fondo7 = new ImageIcon(imagen7.getImage().getScaledInstance(jbtnMinimizar.getWidth(), jbtnMinimizar.getHeight(), Image.SCALE_AREA_AVERAGING));
        jbtnMinimizar.setIcon(fondo7);
        this.repaint();
    }//GEN-LAST:event_jbtnMinimizarMouseEntered

    private void jbtnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMinimizarMouseExited
        //Código para colocar la imagen del boton minimizar
        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/imagenes/Minimizar1.png"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(jbtnMinimizar.getWidth(), jbtnMinimizar.getHeight(), Image.SCALE_AREA_AVERAGING));
        jbtnMinimizar.setIcon(fondo4);
        this.repaint();
    }//GEN-LAST:event_jbtnMinimizarMouseExited

    private void jbtnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinimizarActionPerformed
        //Código para minimizar la ventana
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jbtnMinimizarActionPerformed

    private void jbtnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCerrarMouseEntered
        //Código para colocar la imagen del boton cerrar
        ImageIcon imagen8 = new ImageIcon(getClass().getResource("/imagenes/Cerrar2.png"));
        Icon fondo8 = new ImageIcon(imagen8.getImage().getScaledInstance(jbtnCerrar.getWidth(), jbtnCerrar.getHeight(), Image.SCALE_AREA_AVERAGING));
        jbtnCerrar.setIcon(fondo8);
        this.repaint();
    }//GEN-LAST:event_jbtnCerrarMouseEntered

    private void jbtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCerrarMouseExited
        //Código para colocar la imagen del boton cerrar
        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/imagenes/Cerrar1.png"));
        Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(jbtnCerrar.getWidth(), jbtnCerrar.getHeight(), Image.SCALE_AREA_AVERAGING));
        jbtnCerrar.setIcon(fondo5);
        this.repaint();
    }//GEN-LAST:event_jbtnCerrarMouseExited

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed
        Salida obj3 = new Salida(); //Se crea un objeto de la clase Salida
        obj3.setVisible(true); //Se habilita la vision de la ventana Salida
        dispose(); //Se quita la ventana Juego
    }//GEN-LAST:event_jbtnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (deuce2 == 0) {

            if (jugad1.getPuntaje() >= 0 && jugad1.getPuntaje() < 30) {
                jugad1.setPuntaje(jugad1.getPuntaje() + 15);
                jLabel1.setText(String.valueOf(jugad1.getPuntaje()));
            } else if (jugad1.getPuntaje() == 30 && jugad2.getPuntaje() < 40) {
                jugad1.setPuntaje(jugad1.getPuntaje() + 10);
                jLabel1.setText(String.valueOf(jugad1.getPuntaje()));
            } else if (jugad1.getPuntaje() == 40 && jugad2.getPuntaje() < 40) {

                jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
                jLabel1.setText("Game");
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                jLabel2.setText("Ganador del juego: " + jugad2.getNombre());
                jLabel2.setVisible(true);
            } else if (jugad2.getPuntaje() == 40 && jugad1.getPuntaje() == 30) {
                jugad1.setPuntaje(jugad1.getPuntaje() + 10);
                jLabel1.setText(String.valueOf(jugad1.getPuntaje()));
                jLabel5.setVisible(true);
                deuce2 = 1;
                deuce = 1;

            }
        } else if (jugad2.getPuntaje() == 40 && jugad1.getPuntaje() == 40) {

            jugad1.setPuntaje(jugad1.getPuntaje() + 1);
            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
            jLabel1.setText("A: 40");
            jLabel5.setVisible(false);

        } else if (jugad2.getPuntaje() == 40 && jugad1.getPuntaje() == 41) {

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
            jLabel1.setText("Game");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jLabel2.setText("Ganador del juego: " + jugad2.getNombre());
            jLabel2.setVisible(true);

        } else if (jugad2.getPuntaje() == 41 && jugad1.getPuntaje() == 40) {

            jugad2.setPuntaje(jugad2.getPuntaje() - 1);
            jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 28));
            jLabel7.setText(String.valueOf(jugad1.getPuntaje()));
            jLabel5.setVisible(true);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (deuce == 0) {

            if (jugad2.getPuntaje() >= 0 && jugad2.getPuntaje() < 30) {
                jugad2.setPuntaje(jugad2.getPuntaje() + 15);
                jLabel7.setText(String.valueOf(jugad2.getPuntaje()));
            } else if (jugad2.getPuntaje() == 30 && jugad1.getPuntaje() < 40) {
                jugad2.setPuntaje(jugad2.getPuntaje() + 10);
                jLabel7.setText(String.valueOf(jugad2.getPuntaje()));
            } else if (jugad2.getPuntaje() == 40 && jugad1.getPuntaje() < 40) {

                jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
                jLabel7.setText("Game");
                jButton2.setEnabled(false);
                jButton1.setEnabled(false);
                jLabel2.setText("Ganador del juego: " + jugad2.getNombre());
                jLabel2.setVisible(true);
            } else if (jugad1.getPuntaje() == 40 && jugad2.getPuntaje() == 30) {
                jugad2.setPuntaje(jugad2.getPuntaje() + 10);
                jLabel7.setText(String.valueOf(jugad2.getPuntaje()));
                jLabel5.setVisible(true);
                deuce = 1;
                deuce2 = 1;

            }
        } else if (jugad1.getPuntaje() == 40 && jugad2.getPuntaje() == 40) {

            jugad2.setPuntaje(jugad2.getPuntaje() + 1);
            jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
            jLabel7.setText("A: 40");
            jLabel5.setVisible(false);

        } else if (jugad1.getPuntaje() == 40 && jugad2.getPuntaje() == 41) {

            jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
            jLabel7.setText("Game");
            jButton2.setEnabled(false);
            jButton1.setEnabled(false);
            jLabel2.setText("Ganador del juego: " + jugad2.getNombre());
            jLabel2.setVisible(true);

        } else if (jugad1.getPuntaje() == 41 && jugad2.getPuntaje() == 40) {

            jugad1.setPuntaje(jugad1.getPuntaje() - 1);
            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28));
            jLabel1.setText(String.valueOf(jugad1.getPuntaje()));
            jLabel5.setVisible(true);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jugad1.setPuntaje(0);
        jugad2.setPuntaje(0);
        jLabel1.setText("0");
        jLabel7.setText("0");
        jButton2.setEnabled(true);
        jButton1.setEnabled(true);
        jLabel5.setVisible(false);
        jLabel1.setVisible(true);
        jLabel7.setVisible(true);
        jLabel2.setVisible(false);
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 28));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28));
        deuce = 0;
        deuce2 = 0;

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Salida obj3 = new Salida(); //Se crea un objeto de la clase Salida
        obj3.setVisible(true); //Se habilita la vision de la ventana Salida
        dispose(); //Se quita la ventana Juego

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblBarra;
    private javax.swing.JLabel jLblIcono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnMinimizar;
    private javax.swing.JLabel jlblFoto1;
    private javax.swing.JLabel jlblFoto2;
    private javax.swing.JLabel jlbljugador1;
    private javax.swing.JLabel jlbljugador2;
    // End of variables declaration//GEN-END:variables
}
